title: "The Apprentice Scholar Library"
description: "Explaining science to myself"
baseurl: ""
url: "https://ntrdxplnr.github.io"

markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    line_numbers: false

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'


# No external theme: weâ€™ll use our own layout
theme: null

# Nice permalinks
permalink: /:categories/:title/
